### ISSUE TITLE
Problem: Cannot schedule job for specific minutes 20-59 in specific month

### ISSUE THREAD

**Issue by jamesvl** [quantum-elixir/quantum-core#325]
I receive an error whenever I try to schedule a job with this cron definition in my config:

`"20 8 25-31 May 1-5"`

    [warn] Invalid Schedule ~e[20 8 25-31 5 1-5 *] provided for job #Reference<>.
    No matching dates found. The job was removed.

In fact, _any_ minute that I enter between 20-59 (inclusive) will give me the same error.

However, these all work fine, including the same minute spec for June:

`"0 8 25-31 May 1-5"`
`"19 8 1-30 May 1-5"`
`"55 8 1-30 Jun 1-5"`

Am I missing something about how the cron format works?

**Comment by maennchen** [comment]
Hmm. This should not happen. I can think of obe reason why that happens.

Could you try to set the following config and try again?

  config :crontab, max_runs: 100_000

**Comment by jamesvl** [comment]
Just tried it- I still get the same error though.

**Comment by maennchen** [comment]
@jamesvl If you recompile the `crontab` dependency, this config will solve the problem.

You can recompile like this (be sure to do it for every environment):

```bash
mix deps.compile crontab --force
```

The reason this happens, is that the `crontab` dependency needs to search for time candidates. A lot of that is based on guessing. It will only make `10_000` guesses by default.

**Comment by maennchen** [comment]
This is the same problem as https://github.com/jshmrtn/crontab/issues/48 by the way.

**Comment by maennchen** [comment]
@jamesvl Can you try with the newest `crontab` version?

**Comment by maennchen** [comment]
Close because of inactivity.
