### ISSUE TITLE
Problem: Missing Icon for Organisation

### ISSUE THREAD

**Issue by maennchen** [quantum-elixir/quantum-core#327]
It would be really cool if we had an Icon for the organisation.

**Comment by maennchen** [comment]
I'd like this one. We'd have to ask for permission though since we could not give credit everywhere.

https://thenounproject.com/andrewforrester/icon/514787/#

**Comment by maennchen** [comment]
@c-rack Thank you very much.

I'd really like to go in the direction of the name (Physics) and if it works well also include time in the logo. The clock as the main subject of the logo is a little boring in my opinion.

**Comment by maennchen** [comment]
@c-rack According to our C4 process, we should take your suggestion and continue to improve on that.

**Comment by c-rack** [comment]
@maennchen I have updated the logo with a reference to physics:
https://github.com/c-rack/quantum-elixir-logo/blob/master/quantum-elixir-logo.svg

I really like the symbiosis of a clock an the letter Q (for quantum), now with the physics element, its even better, I agree.

Shall we start with this one until a better proposal comes up?

**Comment by maennchen** [comment]
@c-rack Yes, go ahead :)

**Comment by c-rack** [comment]
The repro is transferred and the orga avatar is updated:
https://github.com/quantum-elixir/quantum-elixir-logo
