### ISSUE TITLE
Problem: Process.monitor of remote process not working as expected

### ISSUE THREAD

**Issue by maennchen** [quantum-elixir/quantum-core#334]
I found that our solution in [`Quantum.Util.start_or_link/1`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/util.ex#L6) does not work as expected.

This will cause this error on node disconnect:

```
10:10:23.827 [error] Supervisor received unexpected message: {:DOWN, #Reference<0.3175945100.3353870340.142203>, :process, #PID<14627.118.0>, :noconnection}
```

**Comment by redink** [comment]
hmm, I want to help.

But, I can't reproduce the issue. I found the error message from https://github.com/erlang/otp/blob/OTP-20.3.2/lib/stdlib/src/supervisor.erl#L631

I think it should due to one supervisor process monitor one remote process, but I can't find where the code in quantum-core.

**Comment by maennchen** [comment]
@redink What happens if you start & connect two cluster nodes and then quit the one that has the `TaskStagesSupervisor` running? Does the other node start a new supervisor?

**Comment by maennchen** [comment]
@redink This is the culprit: https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/util.ex#L10-L17 

The function is used in many `start_link` functions.

**Comment by redink** [comment]
But 
```elixir
  @spec start_or_link(GenServer.on_start()) :: GenServer.on_start()
  def start_or_link({:error, {:already_started, pid}}) when is_pid(pid) do
    Process.link(pid)
    {:ok, pid}
  end

  def start_or_link(other) do
    other
  end
```

these codes just invoking `Process.link/1` rather than `Process.monitor/1`.

The message `{:DOWN, #Reference<0.3175945100.3353870340.142203>, :process, #PID<14627.118.0>, :noconnection}` only from `Process.monitor/1`, https://hexdocs.pm/elixir/Process.html#monitor/1

And if we use `Process.link/1`, the crash message will be `{:EXIT, from, reason}` http://erlang.org/doc/man/erlang.html#process_flag-2

**Comment by redink** [comment]
![image](https://user-images.githubusercontent.com/3191073/38241056-d138925c-3763-11e8-8067-ff38bd423649.png)

after node 2 disconnect node 1, node 1 not affected by anything, and node 2 will start the new task stage supervisor process.

**Comment by maennchen** [comment]
@redink Can you force quit the application instead of `Node.disconnect`?

**Comment by redink** [comment]
![image](https://user-images.githubusercontent.com/3191073/38243480-39c6624e-376a-11e8-8f22-18a468ec465c.png)

I force quit the node 1, and node 2 not affected by anything.

**Comment by maennchen** [comment]
@redink You need to force quit the node with currently has the global job on it. In your screenshot you would've to quit node 2 instead.

**Comment by maennchen** [comment]
I did some research on how to solve this problem. The cleanest solution would be to use a library like [`swarm`](https://github.com/bitwalker/swarm) to orchestrate the workers.

Swarm will also bring the advantage that conflicting workers can be merged together.
