### ISSUE TITLE
Question: Runtime jobs performed at the same time

### ISSUE THREAD

**Issue by mertkahyaoglu** [quantum-elixir/quantum-core#336]
Hello everyone,

In my project, I'm adding a new job that runs every 10 seconds for every POST requests. Although these jobs are added in different times, they are executed at the same. The newly added ones are waiting for the first one to execute altogether. How can I make these jobs run independent from each other?  I apologize if there is already an easy solution for this that I missed.

Here is the code that I'm using from the docs;
```elixir
Notifi.Scheduler.new_job()
      |> Quantum.Job.set_name(:crawler)
      |> Quantum.Job.set_schedule(~e[*/10 * * * * *]e)
      |> Quantum.Job.set_task(fn -> IO.puts "tick:" <> params["id"] end)
      |> Notifi.Scheduler.add_job()
```

**Comment by c-rack** [comment]
Have you tried to give your job distinct names?

**Comment by mertkahyaoglu** [comment]
@c-rack Yes, I did but it didn't work.

```elixir
Quantum.Job.set_name(params["id"] |> String.to_atom)
```

**Comment by maennchen** [comment]
@mertkahyaoglu What do you mean when you say that they are waiting for the first one?

They should all be executed at the same time (always at full 10 seconds (00, 10, 20, 30, 40, 50).

**Comment by mertkahyaoglu** [comment]
> They should all be executed at the same time (always at full 10 seconds (00, 10, 20, 30, 40, 50).

@maennchen I don't want them to be executed at the same time. For example I add a job which is meant to run for every 10 seconds. After 5 seconds I add another job. I expect to see the last job to be executed 10 seconds after it is created but it is executed after 5 seconds together with the first one.

**Comment by maennchen** [comment]
@mertkahyaoglu The schedule `~e[*/10 * * * * *]e` means something like `At every 10th second`.

There is no easy way to schedule something every 10 seconds after it was scheduled.

This is also why we opened the issue #268.

If you really want to use it this way, you could implement it via a little hack (pseudo code, not tested):

```elixir
%{second: second} = NaiveDateTime.utc_now()
second_remainder = rem(second, 10)
schedule = Crontab.CronExpression.Parser.parse!(second_remainder <> "/10, true)

Notifi.Scheduler.new_job()
|> Quantum.Job.set_name(:crawler)
|> Quantum.Job.set_schedule(schedule)
|> Quantum.Job.set_task(fn -> IO.puts "tick:" <> params["id"] end)
|> Notifi.Scheduler.add_job()
```

**Comment by maennchen** [comment]
@mertkahyaoglu Since this is already covered by #268, I'll close the issue.
