### ISSUE TITLE
Revise versioning policy

### ISSUE THREAD

**Issue by hauleth** [quantum-elixir/quantum-core#337]
I have seen a lot of retired versions on hex.pm, what is reasoning for such policy?

Also commit f5fa79677046fc507f2a70ef38ce82193a88c577 introduced breaking change in form of [update of supported Elixir version](https://github.com/quantum-elixir/quantum-core/commit/f5fa79677046fc507f2a70ef38ce82193a88c577#diff-6023be6004fce4718dad3dafb576d258L15) and that wasn't stated in version number (it was minor version bump while it should be major version bump).

**Comment by maennchen** [comment]
https://semver.org/

> What should I do if I update my own dependencies without changing the public API?
> 
> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

**Comment by maennchen** [comment]
@hauleth I have also checked some bigger libraries in the ecosystem and checked if they bumped the major version when the elixir requirement changed. I have found no instance where the major was bumped.

For example check `phoenix` and `ecto`.

**Comment by maennchen** [comment]
@hauleth Would you like to discuss the issue further or should I close the issue?
