### ISSUE TITLE
Problem: Add structured metadata to logs

### ISSUE THREAD

**Issue by isaacsanders** [quantum-elixir/quantum-core#339]
Hey all,

I have really enjoyed quantum so far, and I wanted to document some thoughts I have had.

The use of GenStages is helpful when approaching a system that has data to share, but I am not sure if the system currently exposes the results of the completed jobs.

I have been returning information about the results of the job runs that I would like to gather, aggregate , & display. Currently I have to change the jobs to do that, and I am happy to do that, but if there was a stage that used the BroadcastDispatcher, sharing the execution results with the user, that could make a system that decoupled the jobs from the systems that observe them.

**Comment by maennchen** [comment]
Hi @isaacsanders 

Glad to hear that you like the library :)

I would be very happy to accept a PR for this. If you're interested, please go ahead!

**Comment by maennchen** [comment]
Small note: We're using the DynamixSupervisor which is expected to be the last stage in the chain and does not emit any events. So there's currently no place to hook into the results.

**Comment by isaacsanders** [comment]
I've recently worked on implementing structured logging, and I think the solution may be in the logs. Currently the logs lack metadata and add some of their own structure. I think the library's logging could be better if it tried to build more of a structured logging approach. More metadata, thinner messages.

Adding something similar to Ecto's LogEntry could be an approach that might yield some interesting results.

**Comment by maennchen** [comment]
@isaacsanders That sound like a good approach. I'm renaming the issue to reflect that idea.

**Comment by maennchen** [comment]
> to make metrics gathering and analytics possible

will be handled via #415
