### ISSUE TITLE
Problem: Jobs don't get executed when time is set on app startup (ntp)

### ISSUE THREAD

**Issue by tooreht** [quantum-elixir/quantum-core#342]
## Environment
**elixir**: Elixir 1.6.5 (Compiled with OTP 20) and Elixir 1.6.6 (Compiled with OTP 21)
**quantum**: 2.2.7
**timex**: 3.3.0
**nerves**: 1.0.1

## Description
On a nerves project, when I set time per ntp before firmware app (using Quantum.Scheduler) is started, the jobs don't get executed. They only get added and the next execution is broadcasted. The timezone is explicitly set to UTC in quantum config.

Without setting the time (starting at epoch) the jobs run smoothly. As far as I understand it, quantum is started by the main app, at this point the ntp time is already set. So I don't get why the jobs are not executed.

**Comment by maennchen** [comment]
@tooreht It is really important that the time is set before the `Scheduler` is started. If it is not, the scheduler will need some time to catch up to the current time.

Can you make sure that the time is set before the Scheduler is started?

**Comment by tooreht** [comment]
@maennchen I implemented the `init` callback on my `Scheduler` module with a print statement. I observed on rpi3 boot, that my `Scheduler` gets called after the time is set via ntp and also after the main app has started. Is this a valid way to check the `Scheduler` startup?

Sometimes the job gets executed once as an `ASAP` broadcast. Really strange!

The only special configuration I can think of is the following:
```elixir
# Not possible on readonly filesystem
config :tzdata, :autoupdate, :disabled
```
But I think this shouldn't cause the issue, right?.

**Comment by maennchen** [comment]
@tooreht Could you please enable debug logging and send some logs when it fails?

https://github.com/quantum-elixir/quantum-core#troubleshooting

**Comment by maennchen** [comment]
@tooreht As expected the quantum scheduler is initializes with a date sometime in 1970 and then tries to catch up to the current date as soon as the date is set. I don't know a way to prevent that without preventing quantum to start until the date is correct.

**Comment by maennchen** [comment]
@tooreht I don't think that is something that this library should address directly but rather something that should happen before this library starts. I'm therefore closing the issue.

If you have any questions regarding that ticket, please feel free to reopen it.
