### ISSUE TITLE
Question: Is there a way to ask Quantum if there are any currently running jobs?

### ISSUE THREAD

**Issue by tomekowal** [quantum-elixir/quantum-core#344]
I have a couple of jobs that run daily at different times and take a various amount of time to complete (from seconds to a couple of hours).
Each job saves its start time and end time in the database,
but if we restart the application while the job is running,
it doesn't save its end time and looks as if it was still running.

Is there a way to ask quantum about currently running jobs based on the supervision tree?

If not: would you accept a PR with such feature or is it out of project scope?

**Comment by maennchen** [comment]
Currently this is not possible. It should however be really simple to implement.

There is a GenServer tracking running tasks. It is used to stop tasks from overlapping.

https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/task_registry.ex

Currently this server has no public available api. But I would accept a PR opening up that interface to the public.
