### ISSUE TITLE
Multi-node clusters and GenServer exits

### ISSUE THREAD

**Issue by doughsay** [quantum-elixir/quantum-core#345]
Hi, I'm trying to figure out if it's possible to prevent the error from the scheduler genserver when connecting a new node to a cluster.  I know this has been discussed already in #311, but I'm still a little confused...

here's an example Application.ex that I have:

```elixir
defmodule QuantumTest.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # connect to existing nodes BEFORE starting quantum
    for i <- 1..6, do: Node.connect(:"qt#{i}@127.0.0.1")

    # wait for... what?
    # :timer.sleep(1000)

    children = [
      QuantumTest.Scheduler
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: QuantumTest.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

When I start my first iex session (`iex --name qt1@127.0.0.1 -S mix`), it boots just fine, without any problems.  When I boot the second one (`iex --name qt2@127.0.0.1 -S mix`), it logs an error:

```
17:35:29.105 [error] GenServer QuantumTest.Scheduler.ExecutorSupervisor terminating
** (stop) killed
Last message: {:EXIT, #PID<0.232.0>, :killed}
State: %ConsumerSupervisor{args: {QuantumTest.Scheduler.ExecutionBroadcaster, QuantumTest.Scheduler.Task.Supervisor, QuantumTest.Scheduler.TaskRegistry}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: QuantumTest.Scheduler.ExecutorSupervisor, producers: %{#Reference<0.1712272034.1835532289.184698> => {{#PID<0.235.0>, #Reference<0.1712272034.1835532289.184698>}, 0, 0, 25, 50}}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [{QuantumTest.Scheduler.Task.Supervisor, QuantumTest.Scheduler.TaskRegistry}]}, :temporary, 5000, :worker, [Quantum.Executor]}}
```

According to my understanding, I'm connecting to the existing node BEFORE starting the quantum process.  But it still logs an error, even if the connection has been successfully ahead of time.

If I introduce a 1 second sleep (as seen commented out in the code above), everything works great, and quantum boots up gracefully with no error on any subsequent node after the first.  Why does the 1 second sleep help?

**Comment by maennchen** [comment]
If you start a process with the name `{:global, atom()}`, the cluster only starts that process once per cluster. If the node starts before it is connected to the rest of the cluster this means that both the new node and the rest of the cluster have a process running with the same name.

Since the name must be globally unique, one of them will be killed.

My plan is to use [`swarm`](https://github.com/bitwalker/swarm) in the future to orchestrate the workers. I've no come around to implement this already. This will solve two problems at one:

* Nodes can connect to an existing cluster. Both states can be merged together.
* If a node disconnects without being properly stoped (eg. network split / power issues / process killed etc.) the rest of the cluster does not restart the node somewhere else. (#334)

**Comment by doughsay** [comment]
@maennchen I think I understand the basic concept behind how `:global` works, but your statement here is what I don't get: "If the node starts before it is connected to the rest of the cluster this means that both the new node and the rest of the cluster have a process running with the same name"

See my code that I included above, I *am* connecting to the cluster before starting the quantum process.  From my understanding the code that starts a global process doesn't get run until the quantum scheduler process gets started, is this not the case?

Also, see my comment above about the `:timer.sleep` call.  If I insert that one second sleep, then the error goes away, indicating that the node is indeed getting connected to the cluster and the name collision never happens.

My question was more about why the sleep would make a difference; why can't just ensuring that the node is getting connected to the cluster before starting the rest of the child processes be enough?

**Comment by zacksiri** [comment]
I've upgraded to the latest version of quantum, when I try to start a multi-node cluster using libcluster I get this 

``` 
17:11:53.855 [info] Application studio exited: Studio.Application.start(:normal, []) returned an error: shutdown: failed to start child: Studio.Scheduler
    ** (EXIT) shutdown: failed to start child: Quantum.TaskRegistry
        ** (EXIT) already started: #PID<43527.2717.0>
{"Kernel pid terminated",application_controller,"{application_start_failure,studio,{{shutdown,{failed_to_start_child,'Elixir.Studio.Scheduler',{shutdown,{failed_to_start_child,'Elixir.Quantum.TaskRegistry',{already_started,<43527.2717.0>}}}}},{'Elixir.Studio.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,studio,{{shutdown,{failed_to_start_child,'Elixir.Studio.Scheduler',{shutdown,{failed_to_start_child,'Elixir.Quantum.TaskRegis
```

it crashes the application, before it used to exit the task but the app would still run

Btw I'm using the ErlangHosts Strategy with libcluster.
