### ISSUE TITLE
[Question] Job fails because Repo not available. 

### ISSUE THREAD

**Issue by sweco-semtne** [quantum-elixir/quantum-core#349]
Hi!
I'm running Quantum as part of a Phoenix application. 
I want to start a job on application reboot that fetches data from the database. 

```
config :myapp, Myapp.Scheduler,
  jobs: [
    {"@reboot", {Cacher, :cache, []}}}
  ]
```

As part of the Application I configure both the Ecto Repo and Quantum. 
However it would seem that the Repo hasn't started when the job tries to execute.  

```
def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Myapp.Repo, []),
      # Start the endpoint when the application starts
      supervisor(MyappWeb.Endpoint, []),
      worker(Myapp.Scheduler, [])
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Myapp.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

```
[error] Task #PID<0.617.0> started from #PID<0.615.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Ecto.Registry, nil, 3)
    (ecto) lib/ecto/registry.ex:18: Ecto.Registry.lookup/1
    (ecto) lib/ecto/adapters/sql.ex:251: Ecto.Adapters.SQL.sql_call/6
    (myapp) lib/myapp/cacher.ex:273: Cacher.cache/0
    (quantum) lib/quantum/executor.ex:98: anonymous fn/2 in Quantum.Executor.run/3
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<8.53958586/0 in Quantum.Executor.run/3>
    Args: []
```

Is there an easy way to start a job at application start and make sure that the Repo is already started?

ps.
Thanks for a great library!

**Comment by maennchen** [comment]
I don't have the slightest idea.

Normally the workers should be started sequentially and therefore the scheduler should not start before the repo is up. (At least that's how I believe that it is working.)

**Comment by barkerja** [comment]
@sweco-semtne You could potentially use `Application.ensure_started/2` in your scheduled job. See https://hexdocs.pm/elixir/Application.html#ensure_started/2

**Comment by maennchen** [comment]
@barkerja I don't think that this works since the repo is in the same app as the scheduler.

**Comment by maennchen** [comment]
@sweco-semtne Do you use the application in s cluster? If yes, does the newest release solve your problem?

**Comment by maennchen** [comment]
Closed because of inactivity
