### ISSUE TITLE
Global vs RunStrategy?

### ISSUE THREAD

**Issue by brandonparsons** [quantum-elixir/quantum-core#362]
Hi there,

I'm just wondering what the difference is between the `global: true` configuration option for `quantum`, and the `Quantum.RunStrategy.Random` strategy.  Will these accomplish the same thing?

If I'm running a cluster, and I only want my jobs to be run once (i.e. non-idempotent), what is the correct way to set this up?

**Comment by zacksiri** [comment]
Global true will make sure you only have 1 scheduler started so 2 jobs won’t be scheduled at the same time. Run strategy Random just randomly chooses which node in the cluster to run, but the job will be scheduled by 1 scheduler.

**Comment by brandonparsons** [comment]
Thanks for the reply @zacksiri - can you clarify the following?

`Run strategy Random just randomly chooses which node in the cluster to run, but the job will be scheduled by 1 scheduler.`

Say I have 4 nodes, `global: false` and a job with RunStrategy `random`.  Will 4 jobs be scheduled every time the cron ticker goes off? Because it's selecting a random node, those four jobs could be run on 1, 2, 3 or 4 nodes depending on the random selection?

**Comment by maennchen** [comment]
@brandonparsons You're correct. The job will be run 4 times because there are 4 schedulers. Since the default strategy is random, they could be run on any node.

**Comment by maennchen** [comment]
@brandonparsons I'm going to close the issue. If you've further question do not hesitate to reopen the issue.
