### ISSUE TITLE
Start job manually?

### ISSUE THREAD

**Issue by ckruse** [quantum-elixir/quantum-core#363]
Hi,

maybe I'm missing something, but is there a way to start a job manually? E.g. for debugging purposes or because it failed earlier.

I know I could just start it by calling the function itself, but that could lead to overlapping jobs...

Best regards,
 CK

**Comment by maennchen** [comment]
This is not intended and there‘s no supported way to do that.

You could try to start the Quantum.Executor by hand though.
See the configs in Quantum to see what you have to provide for its start_link function.

**Comment by ckruse** [comment]
Ok, thanks. And thank you very much for your work!
