### ISSUE TITLE
Problem: Swarm Timeout when scaling cluster

### ISSUE THREAD

**Issue by maennchen** [quantum-elixir/quantum-core#374]
Follow up from #368

## Log:

```
web_3  | 23:41:04.382 [info] Application quantum_swarm exited: QuantumSwarm.Application.start(:normal, []) returned an error: shutdown: failed to start child: QuantumSwarm.Scheduler
web_3  |     ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:track, QuantumSwarm.Scheduler.TaskRegistry, %{mfa: {Quantum.TaskRegistry, :start_link, [%Quantum.TaskRegistry.StartOpts{name: QuantumSwarm.Scheduler.TaskRegistry}]}}}, 15000)
web_3  |         ** (EXIT) time out
web_1  | 23:41:04.386 [error] [swarm on quantum_swarm_umbrella@172.23.0.2] [tracker:start_pid_remotely] ** (exit) exited in: :gen_statem.call({Swarm.Tracker, :"quantum_swarm_umbrella@172.23.0.4"}, {:track, QuantumSwarm.Scheduler.TaskRegistry, %{mfa: {Quantum.TaskRegistry, :start_link, [%Quantum.TaskRegistry.StartOpts{name: QuantumSwarm.Scheduler.TaskRegistry}]}}}, :infinity)
web_1  |     ** (EXIT) shutdown
web_1  |     (stdlib) gen.erl:177: :gen.do_call/4
web_1  |     (stdlib) gen_statem.erl:598: :gen_statem.call_dirty/4
web_1  |     (swarm) lib/swarm/tracker/tracker.ex:1115: Swarm.Tracker.start_pid_remotely/6
web_1  |     (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
web_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

## Reproduction Repository
https://github.com/peek-travel/quantum_swarm

**Comment by maennchen** [comment]
@doughsay I'm not getting this error anymore but this instead:

```
web_5  | 19:33:01.556 [error] [swarm on quantum_swarm_umbrella@172.18.0.14] [tracker:handle_handoff] ** (CaseClauseError) no case clause matching: {:entry, QuantumSwarm.Scheduler.ExecutionBroadcaster, #PID<32732.1428.0>, #Reference<0.3516506690.689963012.197623>, %{mfa: {Quantum.ExecutionBroadcaster, :start_link, [%Quantum.ExecutionBroadcaster.StartOpts{debug_logging: true, job_broadcaster_reference: {:via, :swarm, QuantumSwarm.Scheduler.JobBroadcaster}, name: QuantumSwarm.Scheduler.ExecutionBroadcaster, scheduler: QuantumSwarm.Scheduler, storage: Quantum.Storage.Noop}]}}, {{0, 3}, {1, 3}}}
```

**Comment by doughsay** [comment]
@maennchen I'll update my test application to the latest version and try things again on Monday.  Thanks!

**Comment by jgonera** [comment]
Any updates on this? Seems like it might be the same issue that someone reported two weeks ago:
https://github.com/quantum-elixir/quantum-core/issues/397

I'm hitting this as well using quantum 2.3.4

**Comment by mobileoverlord** [comment]
We are also starting to see this in production on nerves-hub.org. One of our containers will fail to start, but the service is replaced and eventually works

**Comment by doughsay** [comment]
@maennchen have you considered trying out [horde](https://github.com/derekkraan/horde) instead of swarm? I assume that's non-trivial, but I wonder if horde handles things better than swarm does...

**Comment by maennchen** [comment]
@doughsay I didn't know about horde. Do you have some experience with it? Is there a way to handle conflicts with it as well?

**Comment by doughsay** [comment]
I actually don't have any experience with it, but I know that it's been getting a lot of attention lately and getting popular.  Swarm has definitely been around longer; just thought I'd bring it up as an idea to maybe help solve these issues that we're seemingly still having.

**Comment by maennchen** [comment]
Replaced by #411

**Comment by brndnmtthws** [comment]
For anyone else running into this problem, I have found a workaround, but it requires patching Quantum. Here are the steps involved:

1. Apply patch from my fork here: https://github.com/brndnmtthws/quantum-core/commit/a38a59eefb1d2e420c66c0921f26a94c2e74e342. The patch drops the timeout parameter on the call to `Swarm.register_name/5`, thus making the call block forever.
2. Update `mix.exs` with patched version, e.g.:

```elixir
  defp deps do
    [
      {:quantum, git: "https://github.com/brndnmtthws/quantum-core.git"}
    ]
  end
```
3. Adjust the swarm sync timeout in `config.exs`, changing from the default of 5s to 60s:
```elixir
# Increase swarm default sync time.
config :swarm,
  sync_nodes_timeout: 60_000
```

After making those changes, I stopped having crashes at startup from these timeouts. Presumably this is caused by swarm not having enough time to finish syncing before the `Swarm.register_name/5` timeout expires.
