### ISSUE TITLE
Problem: Using Quantum means that `mix test` takes 5-6 seconds to start up

### ISSUE THREAD

**Issue by zanderxyz** [quantum-elixir/quantum-core#385]
Hi,

Quantum is great, thanks very much to all the contributors.

One question - is it possible to only run it in :prod and :dev, so that it doesn't slow down `mix test`? I tried only including it in those environments in my `mix.exs` but this causes a crash when the scheduler isn't found: `{:quantum, "~> 2.3", only: [:dev, :prod]},`.

Thanks

**Comment by maennchen** [comment]
You can easily not start quantum when in the test env. This could look like this:

```elixir
defmodule Acme.Application do
  use Application

  case Mix.env() do
    :test -> @children [
      #... other workers (no Scheduler)
    ]
    _ -> @children [
      # ... other workers
      Acme.Scheduler,
      # ... other workers
    ]
  end

  def start(_type, _args) do
    Supervisor.start_link(@children, [strategy: :one_for_one, name: Acme.Supervisor])
  end
end
```

With the next release the startup-time is also greatly improved when using quantum with `global: false`. You could then also just set `global` to `false` only for the test environment.

**Comment by zanderxyz** [comment]
Thanks very much, this does speed it up a lot, but I believe it does still start swarm. I'll use this for now and then check out the global: false for the next release. 

Appreciate your help.

**Comment by maennchen** [comment]
@zanderxyz Swarm should only block if you actually use it. If no scheduler is started, swarm should not block the tests from running.
