### ISSUE TITLE
Scheduler thinks no nodes are live and fails to execute jobs

### ISSUE THREAD

**Issue by devonestes** [quantum-elixir/quantum-core#386]
Howdy!

So I've noticed a really weird thing happening in production for us recently. When it comes time to run our one scheduled daily job, I see an `Elixir.Enum.EmptyError`. Basically, when Quantum Scheduler is trying to call `Enum.random/1` on the list of available nodes to execute the job, that list is being passed in as an empty list (which of course should be impossible).

Here's the stacktrace from our error monitoring service:

lib/enum.ex in Enum.random/1 at line 1811
lib/quantum/run_strategy/random.ex in Quantum.RunStrategy.NodeList.Quantum.RunStrategy.Random.nodes/3 at line 57
lib/quantum/executor.ex in Quantum.Executor.nodes/4 at line 117
lib/quantum/executor.ex in Quantum.Executor.execute/2 at line 66
lib/task/supervised.ex in Task.Supervised.do_apply/2 at line 89

We're currently running our app clustered in Kubernetes, but we don't have Quantum Scheduler configured as `global: true` (because that was causing other weird errors that we haven't figured out yet). We have two live pods, and when I open a remote console to the cluster, I'm seeing two live nodes in there, so the cluster is forming properly.

Here's the really weird part - these errors started on November 23, but we last deployed to production on November 17. I checked the logs, and nothing has changed in the app since that last deploy on November 17. No random pod restarts or anything like that. Everything's been up and running just fine since November 17. Also, on November 23 and 24 I only saw this happening on one pod, but since November 25 it's been happening in both pods.

So, that's what's up. I'm not sure if y'all will have any ideas as to what's going on here, but if you do it would be much appreciated. I'm continuing to look into it myself, and if I find anything, I'll update here.

**Comment by maennchen** [comment]
@devonestes Hmmm... My best guess is that it could be connected to #374 

Are you able to open observer and see what processes are running below the scheduler?

**Comment by maennchen** [comment]
Since there was no further information, I'll close this ticket. Feel free to re-open if the issue happens again or more information is present.

**Comment by milmazz** [comment]
@maennchen Thanks for looking into this. Tomorrow I'll try to use observer and give you more information about this issue, in the meantime, here you can find the state of the Scheduler process and also from `Swarm.Tracker`:

Scenario:

* Last deploy: February 14
* The first error was seen on February 24 (only on one node), and after that on both nodes every day.
* Quantum version: 2.3.3

```elixir
iex> :sys.get_state PotionWeb.Scheduler
{:state, {:local, PotionWeb.Scheduler}, :rest_for_one,
 {[Quantum.ExecutorSupervisor, Quantum.ExecutionBroadcaster,
   Quantum.JobBroadcaster, Quantum.TaskRegistry,
   Quantum.ClusterTaskSupervisorRegistry, PotionWeb.Scheduler.Task.Supervisor],
  %{
    PotionWeb.Scheduler.Task.Supervisor => {:child, #PID<0.3604.0>,
     PotionWeb.Scheduler.Task.Supervisor,
     {Task.Supervisor, :start_link,
      [[name: PotionWeb.Scheduler.Task.Supervisor]]}, :permanent, :infinity,
     :supervisor, [Task.Supervisor]},
    Quantum.ClusterTaskSupervisorRegistry => {:child, #PID<0.3605.0>,
     Quantum.ClusterTaskSupervisorRegistry,
     {Quantum.ClusterTaskSupervisorRegistry, :start_link,
      [
        %Quantum.ClusterTaskSupervisorRegistry.StartOpts{
          group_name: nil,
          name: PotionWeb.Scheduler.ClusterTaskSupervisorRegistry,
          task_supervisor_reference: PotionWeb.Scheduler.Task.Supervisor
        }
      ]}, :permanent, 5000, :worker, [Quantum.ClusterTaskSupervisorRegistry]},
    Quantum.ExecutionBroadcaster => {:child, #PID<0.3608.0>,
     Quantum.ExecutionBroadcaster,
     {Quantum.ExecutionBroadcaster, :start_link,
      [
        %Quantum.ExecutionBroadcaster.StartOpts{
          debug_logging: true,
          job_broadcaster_reference: PotionWeb.Scheduler.JobBroadcaster,
          name: PotionWeb.Scheduler.ExecutionBroadcaster,
          scheduler: PotionWeb.Scheduler,
          storage: Quantum.Storage.Noop
        }
      ]}, :permanent, 5000, :worker, [Quantum.ExecutionBroadcaster]},
    Quantum.ExecutorSupervisor => {:child, #PID<0.3609.0>,
     Quantum.ExecutorSupervisor,
     {Quantum.ExecutorSupervisor, :start_link,
      [
        %Quantum.ExecutorSupervisor.StartOpts{
          cluster_task_supervisor_registry_reference: PotionWeb.Scheduler.ClusterTaskSupervisorRegistry,
          debug_logging: true,
          execution_broadcaster_reference: PotionWeb.Scheduler.ExecutionBroadcaster,
          name: PotionWeb.Scheduler.ExecutorSupervisor,
          task_registry_reference: PotionWeb.Scheduler.TaskRegistry,
          task_supervisor_reference: PotionWeb.Scheduler.Task.Supervisor
        }
      ]}, :permanent, :infinity, :supervisor, [Quantum.ExecutorSupervisor]},
    Quantum.JobBroadcaster => {:child, #PID<0.3607.0>, Quantum.JobBroadcaster,
     {Quantum.JobBroadcaster, :start_link,
      [
        %Quantum.JobBroadcaster.StartOpts{
          debug_logging: true,
          jobs: [
            %Quantum.Job{
              name: #Reference<0.592199220.754188289.209887>,
              overlap: true,
              run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster},
              schedule: ~e[0 0 * * * *],
              state: :active,
              task: {PotionWeb.Reporting.DailyEmailSender, :run_all, []},
              timezone: :utc
            }
          ],
          name: PotionWeb.Scheduler.JobBroadcaster,
          scheduler: PotionWeb.Scheduler,
          storage: Quantum.Storage.Noop
        }
      ]}, :permanent, 5000, :worker, [Quantum.JobBroadcaster]},
    Quantum.TaskRegistry => {:child, #PID<0.3606.0>, Quantum.TaskRegistry,
     {Quantum.TaskRegistry, :start_link,
      [%Quantum.TaskRegistry.StartOpts{name: PotionWeb.Scheduler.TaskRegistry}]},
     :permanent, 5000, :worker, [Quantum.TaskRegistry]}
  }}, :undefined, 3, 5, [], 0, Quantum.Supervisor,
 {PotionWeb.Scheduler, :potion_web, [name: PotionWeb.Scheduler]}}
```

 And here is the state for `Swarm.Tracker`:

```elixir
iex> :sys.get_state Swarm.Tracker
{:tracking,
 %Swarm.Tracker.TrackerState{
   clock: {1, 1690593},
   nodes: [:"potion@10.57.2.85"],
   pending_sync_reqs: [],
   self: :"potion@10.12.0.52",
   strategy: #<Ring[:"potion@10.57.2.85", :"potion@10.57.1.10"]>,
   sync_node: nil,
   sync_ref: nil
 }}
```
