### ISSUE TITLE
Dynamic job names

### ISSUE THREAD

**Issue by madshargreave** [quantum-elixir/quantum-core#390]
I think it would be useful to extend the `Quantum.Job.set_name/2` function to accept strings as well as this will allow for registering dynamic jobs without risking the atom-memory pitfalls

**Comment by maennchen** [comment]
@madshargreave That's what reference job names are though for. Just create a new job and use its name for future reference.

**Comment by madshargreave** [comment]
@maennchen Ah I missed that from the documentation. Great, thanks 👍

**Comment by maennchen** [comment]
Great, I'll close the ticket then.

**Comment by maennchen** [comment]
The reason why I'm hesitant to add new types to names is that the name will be used in many contexts. For example any storage protocol implementation will need to support all possible types.

To keep the surface as minimal as possible, the two following types are currently supported:

* `atom` => named job, not to be used dynamically
* `ref` => dynamic job

**Comment by leodag** [comment]
Maybe accept only strings and integers besides the current ones? That seems like it should cover the most frequent usecases (numerical identifiers - my use case, which led me here - and user-specified names). Maybe floats too, but floats are always a bit of a pain, and I don't know how hard to handle they'd be for storage backends. Any more complex name should be serializable into a string, if needed.
