### ISSUE TITLE
Compile warning on 2.3.4 with Elixir 1.8.0-otp-21.2.2

### ISSUE THREAD

**Issue by OvermindDL1** [quantum-elixir/quantum-core#393]
```elixir
==> quantum
Compiling 37 files (.ex)
warning: function Quantum.DateLibrary.Timex.tz_to_utc!/2 is undefined (module Quantum.DateLibrary.Timex is not available)
  lib/quantum/date_library.ex:40

warning: function Quantum.DateLibrary.Timex.utc_to_tz!/2 is undefined (module Quantum.DateLibrary.Timex is not available)
  lib/quantum/date_library.ex:47

Generated quantum app
```
If something is dependent on Timex then all code related to it should be compiled only conditionally or else Timex should become a hard dependency.  When depender project is compiling with warnings as errors then it fails to build.

**Comment by c-rack** [comment]
Good catch, thanks!

**Comment by maennchen** [comment]
@OvermindDL1 This problem is caused since the code is compiled conditionally. Timex is not installed and the module Quantum.DateLibrary.Timex is therefore not compiled. Since the config has not specified an alternative, this module is used.

We have some documentation for this topic. First we recommend installing it together with timex and second we write about the date library here: 
https://hexdocs.pm/quantum/date-library.html#content

I would not consider this a bug since this is exactly behaving as intended.

Also, we can nit really change anything about that without causing breaking changes.

Instead I would like to focus n the next major release. Since Elixir 1.8 we can do all of that without using third-party libraries. So we can remove all this stuff, directly use the Elixir API‘s while only maintaining a doc page that mentions how to install tzdata to get timezone support.

**Comment by OvermindDL1** [comment]
Well the calls to the Timex accessing module can be conditionally compiled as well (although that module should probably have stubs at this point) via something like this inline in the function body `unquote(if(Code.ensure_compiled?(Quantum.DateLibrary.Timex), do: quote(do: Quantum.DateLibrary.Timex.tz_to_utc!), else: Quantum.WhateverFallback.YouWant)(arg1, arg2)` or other variants on it as wanted.  :-)

**Comment by OvermindDL1** [comment]
> If the installation steps are followed, this error will not happen.

The installation steps are currently showing to manually add the timex dependency, which is something that quantum itself should be doing if it is a required dependency however?  When quantum is being used by another library then the users of that library would not see that requirement if it was not explicitly brought in by the intermediary as well.

**Comment by maennchen** [comment]
@OvermindDL1 Quantum does not explicitly depend on timex. Both timex and calendar are valid options or any other implementation of the behaviour.

Since it is not possible to detect what implementations of a behaviour exist, this has to be configured.

**Comment by OvermindDL1** [comment]
> Since it is not possible to detect what implementations of a behaviour exist, this has to be configured

But it is fairly easy to determine if something like Timex is loaded however, and thus to conditionally not compile in any code that uses it when it does not exist.  :-)

**Comment by maennchen** [comment]
@OvermindDL1 

The only thing we can do without breaking the API is the following:

Load the `date_library` config. Check if the configured module exists. Otherwise raise an error at compile time.

This would give a clearer error than the current warnings where we could explain the situation.

Currently `quantum` does not enforce any date library specifically. This is the same as if you would use `phoenix` without `cowboy` or any other plug adapter.

**Comment by OvermindDL1** [comment]
> The only thing we can do without breaking the API is the following:

Well that's the thing, using something like `unquote(if(Code.ensure_compiled?(Quantum.DateLibrary.Timex), do: quote(do: whatever_if_loaded()), else: quote(do: whatever_fallback()))` then you get to keep the same public API but only adjust the insides as necessary.  :-)

It works like (in the specific example of the OP functions), instead of doing:
```elixir
  @date_library Application.get_env(:quantum, :date_library, Quantum.DateLibrary.Timex)
```
You'd instead do (you don't even need unquote stuff for the specific example in Quantum as it can be done at the top level):
```elixir
  @date_library cond do
    Application.get_env(:quantum, :date_library, false) -> Application.get_env(:quantum, :date_library)
    Code.ensure_compiled?(Quantum.DateLibrary.Timex) -> Quantum.DateLibrary.Timex
    Code.ensure_compiled?(Quantum.DateLibrary.Calendar) -> Quantum.DateLibrary.Calendar
    true -> throw "Please install the Timex library by adding `{:timex, "~> 3.0"}` to your dependencies or upgrade to a version of Elixir that contains the `Calendar` library"
  end
```
And that will choose whatever the user chooses by default, else it falls back to timex if it's available, else it falls back to Calendar if its available, else it falls back to throwing an instructional example error message, all of this happens only at compile-time and not runtime just as the prior code did.  :-)

Clearer error messages and hard errors on unrecoverable conditions are always best.  :-)

**Comment by maennchen** [comment]
I guess this sounds reasonable. We'd need to do this in the application module as well though. I'll have a look.

**Comment by maennchen** [comment]
@OvermindDL1 Hmm. Works better in theory because this produces a circular dependency.

**Comment by maennchen** [comment]
```
==> quantum
Compiling 37 files (.ex)

== Compilation error in file lib/quantum/application.ex ==
** (CompileError)  deadlocked waiting on module Quantum.DateLibrary
    lib/quantum/application.ex:8: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

== Compilation error in file lib/quantum/date_library/timex.ex ==
** (CompileError)  deadlocked waiting on module Quantum.DateLibrary
    (elixir) lib/code.ex:892: Code.ensure_compiled/1
    (elixir) lib/code.ex:912: Code.ensure_compiled?/1
    (elixir) lib/module.ex:1339: anonymous fn/4 in Module.check_behaviours/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/module.ex:1314: Module.check_behaviours_and_impls/4

== Compilation error in file lib/quantum/date_library.ex ==
** (CompileError)  deadlocked waiting on module Quantum.DateLibrary.Timex
    (elixir) lib/code.ex:892: Code.ensure_compiled/1
    (elixir) lib/code.ex:912: Code.ensure_compiled?/1
    lib/quantum/date_library.ex:17: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

         lib/quantum/application.ex => Quantum.DateLibrary
  lib/quantum/date_library/timex.ex => Quantum.DateLibrary
        lib/quantum/date_library.ex => Quantum.DateLibrary.Timex
```

**Comment by OvermindDL1** [comment]
Ah they depend on each other, in that case move the module configuration test to a different module with a function that just returns the result and call that function, something like:
```elixir
defmodule Quantum.Config do
  @date_library cond do
    Application.get_env(:quantum, :date_library, false) -> Application.get_env(:quantum, :date_library)
    Code.ensure_compiled?(Quantum.DateLibrary.Timex) -> Quantum.DateLibrary.Timex
    Code.ensure_compiled?(Quantum.DateLibrary.Calendar) -> Quantum.DateLibrary.Calendar
    true -> throw "Please install the Timex library by adding `{:timex, "~> 3.0"}` to your dependencies or upgrade to a version of Elixir that contains the `Calendar` library"
  end

  def date_library(), do: @date_library
end
```
Then as long as you just call that function directly via `Quantum.Config.date_library()`, which you can use like `Quantum.Config.date_library().some_function_on_that_module()` without importing or requiring it (that creates a compile-time dependency) then you are good to go.  :-)

**Comment by maennchen** [comment]
This issue will be solved with Version 3 (already solved on `master`)
