### ISSUE TITLE
Node scaling fails to start child QuantumScheduler

### ISSUE THREAD

**Issue by jacobparry** [quantum-elixir/quantum-core#397]
Whenever we deploy to our production environment (we use 3 nodes), it is common that the second and third node will continue to crash when attempted to be brought up. We generally have to do a full reboot in order to get back to three nodes. This error is what we see when this happens.

2019-02-22 23:10:03.753 level=info module=application_controller msg="Application temp exited: :stopped"
** (MatchError) no match of right hand side value: {:error, {:core, {{:shutdown, {:failed_to_start_child, Core.Jobs.Supervisor, {:shutdown, {:failed_to_start_child, Core.Jobs.QuantumScheduler, {:timeout, {:gen_statem, :call, [Swarm.Tracker, {:track, Core.Jobs.QuantumScheduler.TaskRegistry, %{mfa: {Quantum.TaskRegistry, :start_link, [%Quantum.TaskRegistry.StartOpts{name: Core.Jobs.QuantumScheduler.TaskRegistry}]}}}, 15000]}}}}}}, {Core.Application, :start, [:normal, []]}}}}

**Comment by maennchen** [comment]
Replaced by #411
