### ISSUE TITLE
runtime error bad_action_from_state_function

### ISSUE THREAD

**Issue by robertsithouse** [quantum-elixir/quantum-core#403]
Hello, I have this error, which occurs when the cron job is executed. It seems to happen when I prepare a production release with destilery.

```
11:08:15.022 [error] GenStateMachine #PID<0.2405.0> terminating
** (ErlangError) Erlang error: {:bad_action_from_state_function, {:reply, :undefined, {:error, :timeout}}}
    (stdlib) gen_statem.erl:1290: :gen_statem.parse_actions_reply/7
    (stdlib) gen_statem.erl:1206: :gen_statem.loop_event_actions_list/10
    (ssl) tls_connection.erl:133: :tls_connection.init/1
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by JackSoby** [comment]
I have the same issue running locally, did you ever find a fix?

**Comment by robertsithouse** [comment]
Unfortunately, no. Currently, the system logs are filled with those errors. Everything seems to be working fine tho. Only that actual errors are hard to find between this one

**Comment by maennchen** [comment]
Replaced by #411
