### ISSUE TITLE
Problem: Configuration Documentation diverges from Code

### ISSUE THREAD

**Issue by smaximov** [quantum-elixir/quantum-core#406]
Hello. According to the "Configuration" page of the docs, section "Named jobs"

> For runtime configuration, job names are not restricted to be atoms

I tried to add a job with a `String` name using `Quantum.Job.set_name/2` and got a `FunctionClauseError` (caused by the [`is_atom` guard](https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/job.ex#L93)).

Is this a bug (`set_name/2` should accept other types) or is documentation outdated?

**Comment by smaximov** [comment]
I want to associate a job with some data in a database using a `String` job name, so I can delete the job when the data is gone or prevent creation of duplicate jobs. I have two solutions if a job cannot have a `String` name:

1. I can convert a `String` job name to an atom (which is frowned upon).
2. I can maintain a mapping between a `String` key which references the data in my database and the job's default name (which is a reference).

**Comment by LostKobrakai** [comment]
I'd support that request. Atoms shouldn't be handling arbitrary names and storing refs<=>arbitrary name means I need to keep some lookup table in sync with quantum's jobs.

**Comment by maennchen** [comment]
@smaximov Good Catch, I adapted the documentation to match the code.

@LostKobrakai This was discussed on multiple occasions: #390, #379 
If you want to continue the discussion, please add new arguments to one of the existing issues.

**Comment by Ciboulette** [comment]
Hey, 

As @LostKobrakai and others, I would also to support this request. Indeed, in the system I'm currently building, I really need to schedule jobs dynamically and I don't want to be limited by the Erlang atom limit.

From my point of view, It should not be the hardest work to do to be able to set_name for multiple data types... What do you think? How can I do it until it changes?

**Comment by Ciboulette** [comment]
Any news?

**Comment by maennchen** [comment]
Tracking in #390
