### ISSUE TITLE
New global Strategy

### ISSUE THREAD

**Issue by maennchen** [quantum-elixir/quantum-core#411]
The current situation using `swarm` is not stable enough and produces many non-deterministic problems. The usage of `:global` before `swarm` also produced many issues.

Therefore a new solution should be implemented to tackle those issues.

**Comment by maennchen** [comment]
Thoughts from Slack:

```
tsloughter [7:37 PM]
why not just use a database?

tsutsu [7:38 PM]
@maennchen I’ve always wondered why everything `quantum` does _needs_ to be distributed. It seems to me that there’s an “obvious” factoring `quantum` could do into two components, that allows you to avoid the hardest parts of the distribution problem:

1. one component, a more traditional job [priority-]queue library, serving as the backend for `quantum` to schedule workloads upon, supporting all the things `quantum` currently supports (e.g. jobs with keys where you can’t schedule a second instance of a job that’s already in the queue/in progress.) This part would use `swarm`, in a much simpler way than `quantum` does currently (it’d just be a set of greedy consumers fed by the leader’s queue.)

2. the other component, a cron job _source_—a lighter daemon that just runs in one place (maybe fault-tolerantly, using Erlang’s application failover, but that can be done after-the-fact by integrators who need it) which, upon a crontab entry’s timer firing, _creates_ “job” objects in its job-queue backend. (You could have more than one of these in the cluster, but each one would “own” the jobs it creates, and thus would have its own individual crontab, rather than there being one global crontab.)

This would also allow people to use `quantum` _as_ their jobs library, and so only have one set of jobs infrastructure, which would be _really_ nice. (And maybe things could work the other way as well: if other jobs systems saw `quantum`’s factored jobs library, they’d maybe copy its features, and then they’d become API-compatible enough that the quantum scheduler could offer the option to swap out its own queue backend for one of the existing jobs libraries.)

I feel like, despite this change having little to do with your question as stated, it _might_ be a fix to whatever the headaches are you’re talking about—since you would no longer be trying to do consensus on job _creation_ from a clock source, merely on consumption from a global queue, which is a far more well-studied problem (edited) 

tsloughter [7:38 PM]
if you really need distributed state, if eventual consistency is acceptable I'd say checkout lasp and/or riak_core
but a separate database is a good way to go :slightly_smiling_face:

tsutsu [7:45 PM]
but everything I said is wrong _if_ people are trying to use `quantum` to get things to happen “simultaneously” (in a soft-realtime sense) on multiple machines, using `swarm` as the ahead-of-time synchronization primitive to get each node to have a preloaded in-memory schedule. Then they _need_ the schedule itself to be on all the nodes, so that tasks can execute near-instantaneously with locality.

Is `quantum` being used this way? Because I think it _could_ be used this way… but I don’t think I ever saw it listed as an explicit design goal, so you could just say you don’t support that use-case, to release yourself from the burden of the architecture it requires. (edited) 
```

**Comment by arjan** [comment]
What about using [Horde][horde]'s CRDT for the global execution mode?

As one of the maintainers of Swarm I know that the project is basically in hibernation, there are some open issues that are hard to reproduce / fix and its overall design is also questionable.

Horde seems to have more momentum, and is more modular; I think that it would be possible to replace `:global` with a `Horde.Registry` for the global process runner.

[horde]: https://github.com/derekkraan/horde

**Comment by maennchen** [comment]
@arjan How does Horde manage Handoffs to another node when the node currently running a process shuts down?

**Comment by arjan** [comment]
It does not have anything special but there is a [guide](https://hexdocs.pm/horde/state_handoff.html) explaining how it can be done using trap_exit. However you need to store the handoff state yourself somewhere. Could be done in the CRDT itself though, if it's not too large.

**Comment by maennchen** [comment]
@arjan How would you implement a Handoff Logic via the CRDT?

**Comment by arjan** [comment]
When the node is shutting down you could register the handoff state on the CRDT, and then sleep, to give the CRDT some time to propagate, before the local CRDT shuts down.

That means that the CRDT needs to be started in your supervision tree before the process that wants to handoff, because that way you can be sure the crdt is still around when shutting down the proecess.

I am not sure that this works for large number of processes or a large state, but for me it works.

I implemented something like that [here](https://github.com/arjan/sworm/blob/master/lib/sworm/delegate.ex#L114). I do not start a separate CRDT but use the `Horde.Registry` for this.

Maybe @derekkraan has something smart to say about this as well :-)

**Comment by derekkraan** [comment]
Correct me if I'm wrong, but Quantum uses `swarm` to start a single scheduler that executes cron jobs. If this is the case, then perhaps you don't need to hand off state at all. The consequence would be that you possibly run the same job twice (if system clocks aren't synchronized perfectly), or miss a job (if you happen to shut down a node precisely before a job was set to run).

There are other things to consider:
1. If a node crashes, then there won't be any state to hand off.
2. Handing off state introduces complexity and possibly bugs. If you somehow persist incorrect state, then a restart won't reset your process to a "known good state" anymore, so it's worth considering whether it's worth the effort.

As an aside, I do think Horde would be a good match for distributed Quantum. Horde.Supervisor would restart the scheduler when a node goes missing or shuts down, and Horde.Registry ensures it's only running anywhere in your cluster once, and provides a way to globally address the scheduler process. Additionally, you can tune the underlying CRDT by passing the appropriate option to Horde.Registry and Horde.Supervisor.

**Comment by maennchen** [comment]
@derekkraan Running a job twice is not really a problem. We have a ClockBroadcaster. If we handoff, we would also handoff this one. This makes sure that time is not jumped over or repeated.

I would like to have a handoff feature at least for non-crash situations so that the system continues to run when for example a deployment is updating in K8S. It's clear to me that this will not solve a case with a crash.

If you want to be sure with a crash, I'd point people to the storage adapter solution that we should release stable at the same time as we release a solution to this particular issue.

**Comment by derekkraan** [comment]
@maennchen If you want to replicate the state of the ClockBroadcaster in the cluster so that you can do handoff during deployment scenarios, then you could simply use [`Horde.Registry.put_meta/3`](https://hexdocs.pm/horde/Horde.Registry.html#put_meta/3) in the `terminate/2` callback of the `ClockBroadcaster` process (and then a sleep to ensure it has time to propagate), and [`Horde.Registry.meta/2`](https://hexdocs.pm/horde/Horde.Registry.html#meta/2) in the `init/1` callback. You may consider recording a timestamp in the metadata to ensure that you don't accidentally recover from an old record.

If you tune the CRDT with the `delta_crdt` option, then you can know how long you need to sleep after using `put_meta/3` when the process is terminating to ensure that its data has been synced to the other nodes in the cluster.

**Comment by maennchen** [comment]
@c-rack Would you agree to a new major version without clustering support? I would later add it back as a new feature.

I think it would make sense to get out a stable set of features and later improve on them.

**Comment by maennchen** [comment]
I'm thining it would make sense to split of the global part into a new package.

It would work something like this (isntead of `use Quantum, ...`):

```elixir
defmodule Acme.Scheduler do
  use Quantum[Horde|Swarm|OtherProvider], otp_app: :acme
end
```

The module would then do those things:

* Start Quantum (the whole thing) only in one place
* Start `TaskSupervisor` everywhere
* Register a global name so that it can be used in the whole cluster
* Inject a new `Quantum.Storage`

The new `Quantum.Storage` would do the following things:

* Delegate writes to the cluster state and the original installed storage
* When booting quantum, the state would be consumed from the cluster state with a fallback to the original storage

**Comment by maennchen** [comment]
Needed to build a package for horde:

* Storage Adapter that uses `Horde.Registry.put_meta/3` / `Horde.Registry.meta/2`
* Allow quantum to be started with another `global` name (`{:via, Horde.Registry, Acme.Scheduler}`)
* Allow quantum to be started without `TaskSupervisor` since it will be run separately
* Build `QuantumHorde`that does the follwoing:
  - injects the storage into config
  - injects global name into config
  - disable task supervisor in config
  - starts horde supervisor
  - starts quantum once globally
  - starts task supervisor everywhere

**Comment by maennchen** [comment]
What do you think about this approach @derekkraan / @arjan?

**Comment by arjan** [comment]
I think a solution like this makes a lot of sense.

Distributed state is hard to get right, as we all know. Keeping Quantum focused on the single node case is probably good enough for most people, and reduces a lot of complexity from this library.

I was wondering though, what were the exact issues when you were still using `global` instead of Swarm / Horde? Why did you move away from using it?

**Comment by derekkraan** [comment]
@maennchen I think a pluggable approach makes sense. I know of at least one library (commanded/event_store) that uses postgres advisory locks for ensuring that a process only runs in one place in a cluster, and I think that might be a better option for a large percentage of the users of this library for example.

**Comment by arjan** [comment]
Yeah, I share this sentiment. A CRDT seems quite overkill for what is basically one "singleton-process".

**Comment by maennchen** [comment]
@arjan 

> I was wondering though, what were the exact issues when you were still using global instead of Swarm / Horde? Why did you move away from using it?

For two reasons:

* In the event of a conflict, the states are impossible to merge / hand over since global kills the process and not just terminates it.
* Even though we linked to a process, if the node running the process got killed / network problem etc, the termination was not detected by the other nodes and no new process was started.

**Comment by derekkraan** [comment]
@maennchen 

> In the event of a conflict, the states are impossible to merge / hand over since global kills the process and not just terminates it.

This behaviour is configurable in `:global` via a callback (the third argument) in `register_name/3`.

> Even though we linked to a process, if the node running the process got killed / network problem etc, the termination was not detected by the other nodes and no new process was started.

This seems unlikely. Both links and monitors work in a cluster just fine. If a node is killed (or there is a netsplit), then monitors and links will fire as you would expect.

I recently put together a solution for `commanded/event_store` to solve this problem, and yesterday extracted that out into its own library, Highlander ([docs](https://hexdocs.pm/highlander/Highlander.html), [blog post](https://moosecode.nl/blog/highlander_there_can_be_only_one)).

Perhaps this can serve as inspiration for a solution to the problem of this issue. (Or perhaps it is usable directly)

**Comment by ishikawa** [comment]
@derekkraan Thank you for implementing and publishing Highlander. It's a tiny but amazing library. Recently, we are switching from Horde to Highlander for making only one Quantum scheduler process running.

Horde is also incredible, but it's too powerful and hard to control. Maybe cause we're lack of experience, we had to write some glue code to achieve the goal with Horde. But with Highlander, we can achieve the goal just follow the tutorial.

```elixir
children = [
  supervisor(MyApp.Endpoint, []),
  {Highlander, MyApp.Scheduler}
]
```

And configure jobs to run under `Quantum.RunStrategy.Local`.

```elixir
config :my_app, MyApp.Scheduler,
  run_strategy: Quantum.RunStrategy.Local,
  jobs: [
    ...
  ]
```

Our new scheduled job system (Quantum 3.0 and Highlander / running on Kubernetes cluster) is still in a staging environment and under testing. The current result is good. We changed the number of pods randomly, but Highlander keeps the scheduler process running and there is only one process in Erlang cluster. 🙂

**Comment by derekkraan** [comment]
@ishikawa thanks! I think Highlander is much better suited to this problem than Horde, so it seems like you made a good choice there :+1:. Of course most of the kudos should be directed to the Erlang team, I only repackaged their work (on `:global`) in a slightly different way.

One thing to watch out for is the behaviour of Highlander when there is a network partition affecting your cluster. Highlander will in that case spawn one scheduler process per partition, and that may or may not break your setup.

**Comment by maennchen** [comment]
@ishikawa Thanks :)

I'll push a new minor version soon that will split the main supervisor into two parts:

* `Task.Supervisor` & `Quantum.ExecutorSupervisor` 
* The rest

This will allow to start the first one on every node and the second one via `global` / `Highlander` / `swarm` / `horde` / etc.

I'm planning to publish a package that uses this interface using `global` (simple, no conflict resolution), I'd be very happy if others would be provided by the community.

**Comment by maennchen** [comment]
I pushed a draft PR together with a swarm example. I'd love to get some feedback on it from all of you.

Some community packages based on that (hosted either in the quantum org or also independently) would be great to support multiple providers.

**Comment by maennchen** [comment]
This can now be done externally. Therefore I'm closing this issue.

Please open new issues if you implement an alternative adapter and something is missing.

**Comment by ericdude4** [comment]
This can also be accomplished with Singleton https://github.com/arjan/singleton
