### ISSUE TITLE
Expose Telemetry Metrics

### ISSUE THREAD

**Issue by maennchen** [quantum-elixir/quantum-core#415]
Expose Metrics via Telemetry

**Comment by mrmarcsmith** [comment]
@maennchen I'm happy to explore opening a PR for this.  Is this something you have started? if not, Is there any chance you could give me a shove in the right direction as far as a high level plan? You know this project better than anyone so a little bit of help from you could save me a LOT of time.

**Comment by mrmarcsmith** [comment]
@maennchen if you have time, a quick reply could help me get started on this.

**Comment by maennchen** [comment]
@mrmarcsmith Sorry, i don't really have time right now. I'm on vacation until next week.

It'd be awesome to get a PR with this feature.

I have thought about this at some point. I thought that at least the following events should be recorded:

* add job
* delete job
* update job
* job execution (including return value / error / execution time)

The first three should probably be added to the JobBroadcaster module and the execution in the Executor module.

**Comment by mrmarcsmith** [comment]
That should be enough to get me started! Thank you for replying while on vacation.

**Comment by maennchen** [comment]
Replaced by #453

**Comment by maennchen** [comment]
@mrmarcsmith Released as `v3.2.0` :heart:

**Comment by mrmarcsmith** [comment]
Thank you @maennchen!
