### ISSUE TITLE
How to check when a job will be run next?

### ISSUE THREAD

**Issue by sheharyarn** [quantum-elixir/quantum-core#419]
Pretty much as it says on the can. For example, given a config like this:

```elixir
config :my_app, MyApp.Cron.Scheduler,
  jobs: [
    {"@hourly", {MyApp.Cron.JobA, :run, []}},
    {"@daily", {MyApp.Cron.JobB, :do_something, []}},
  ]
```

How can I check when each of the jobs will be run next? Getting the next run datetime for a [named job](https://hexdocs.pm/quantum/configuration.html#named-jobs) will also be helpful.

**Comment by maennchen** [comment]
For this you can use `crontab` directly: https://hexdocs.pm/crontab/Crontab.Scheduler.html#get_next_run_date/3

**Comment by sheharyarn** [comment]
Ah, I see. I came across the `crontab` package earlier but didn't realize that's what quantum uses underneath. This is exactly what I needed.

Thanks!
