### ISSUE TITLE
Ecto Repo not started error in Quantum Executor

### ISSUE THREAD

**Issue by quinlanjager** [quantum-elixir/quantum-core#421]
I have two jobs scheduled `"@hourly"` that use an Ecto Repo. However, it encounters a "Repo not started" error when running. The jobs do completed (I'm assuming because of our supervisor settings), but I'm trying to track down the root cause to quiet down our logging. This occurs even after our application has been up and running for a while.

Thanks!

```
Task #PID<0.785.0> started from #PID<0.783.0> terminating
** (RuntimeError) could not lookup VetSuccess.Repo because it was not started or it does not exist
    (ecto) lib/ecto/repo/registry.ex:18: Ecto.Repo.Registry.lookup/1
    (ecto) lib/ecto/repo/queryable.ex:137: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (wellness) lib/wellness/transactions/invoices.ex:28: Wellness.Transactions.Invoices.cache_transactions_from_past_day/0
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<7.12665260/0 in Quantum.Executor.run/4>
    Args: []
```

**Comment by fivetwentysix** [comment]
@quinlanjager I have created an example of how to setup Quantum using `Ecto.Repo` in a brand new Phoenix application: https://github.com/fivetwentysix/elixir-phoenix-quantum-example.

Could you kindly try to fork and reproduce the error you're having? Thanks!

**Comment by quinlanjager** [comment]
Hi @fivetwentysix,

Thanks for getting back to me. This was actually not an issue with Quantum. We had a staging version of the app that didn't have the Ecto.Repo initialized _on purpose_. Those staging errors were showing up with our production errors which caused my confusion.
