### ISSUE TITLE
Dependency get failure on latest master. c021b9

### ISSUE THREAD

**Issue by collinmurray** [quantum-elixir/quantum-core#426]
Hi all. We are using the Quantum library in our projects and our CI started failing yesterday.
The error message looks to be quantum related:

```
 * Getting quantum (https://github.com/quantum-elixir/quantum-core.git)
 remote: Enumerating objects: 75, done.        
 remote: Counting objects: 100% (75/75), done.        
 remote: Compressing objects: 100% (49/49), done.        
 remote: Total 2909 (delta 26), reused 73 (delta 26), pack-reused 2834        
 Receiving objects: 100% (2909/2909), 729.82 KiB | 11.40 MiB/s, done.
 Resolving deltas: 100% (1676/1676), done.
 fatal: reference is not a tree: c021b9c929770c4f9237b68cb0754ce6c8008347
 ** (Mix) 
```

I've confirmed this locally:
```
Styx-macs-MacBook-Pro:trixta_space Styx-mac$ mix deps.clean quantum
* Cleaning quantum
Styx-macs-MacBook-Pro:trixta_space Styx-mac$ mix deps.get
* Getting quantum (https://github.com/quantum-elixir/quantum-core.git)
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 2909 (delta 26), reused 73 (delta 26), pack-reused 2834
Receiving objects: 100% (2909/2909), 729.82 KiB | 859.00 KiB/s, done.
Resolving deltas: 100% (1676/1676), done.
fatal: reference is not a tree: c021b9c929770c4f9237b68cb0754ce6c8008347
** (Mix) Command "git --git-dir=.git checkout --quiet c021b9c929770c4f9237b68cb0754ce6c8008347" failed
```
It seems like the current master is failing to check out against that SHA. This is likely due to the currently in-progress 2.4.0 release and a missed tag.

I'm bringing it up as currently having `{:quantum, git: "https://github.com/quantum-elixir/quantum-core.git"},` will cause your dependency pulls to fail. 

**TEMPORARY RESOLUTION**
I've changed my mix.ex reference to `{:quantum, git: "https://github.com/quantum-elixir/quantum-core.git", ref: "a49df9f"},`, which is the v2.3.4 release SHA, as a quickfix until the rollout of 2.4.0 happens.

Please let me know if I'm misunderstanding anything. I'll resolve and remove this issue once the release is out.

**Comment by maennchen** [comment]
If you want to make sure that a dependency always works, adding a ref like you did is required.

I‘ll try to get out the unreleased changes out as v3 soon.
