### ISSUE TITLE
Job error reporting

### ISSUE THREAD

**Issue by nickewing** [quantum-elixir/quantum-core#430]
Is there a recommended way to monitor errors raised by jobs invoked by Quantum?  I am attempting to report such errors to an external service for logging.  I have looked through the documentation but all I could find there was:

> The OTP Supervision Tree is initiated by the user of the library. Therefore the error handling can be implemented via normal OTP means. See Supervisor.Spec for more information.

I couldn't find a way to monitor the child job processes for failures in the docs on Supervisor or Supervisor.Spec.  I tried several recommendations from various places on the internet but with no success.

Any guidance on this would be greatly appreciated.

**Comment by maennchen** [comment]
@nickewing We‘ve planned to implement a solution for statistics via #415. The events there would also include the result of the jobs.

Currently there’s only two ways:
* Enable Debug Logging and check the result
* Wrap the task in another function that catches all errors and log them there.

Do you think that #415 would solve your problem nicely?

**Comment by nickewing** [comment]
@maennchen Unfortunately it doesn't look like debug logging includes errors thrown in jobs.  I have setup the following task to run repeatedly, but as you can see below, the error is not included in the debug messages.

```elixir
defmodule Example.Tasks.TestTask do
  def run() do
    raise("Fail")
  end
end
```

```
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Scheduling job for execution #Reference<0.869436057.1393033218.155314>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576460611610 (2020-03-11T10:52:25)
[debug] [:nonode@nohost][Elixir.Quantum.Executor] Task for job #Reference<0.869436057.1393033218.155314> started on node :nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.Executor] Execute started for job #Reference<0.869436057.1393033218.155314>
[error] Task #PID<0.737.0> started from #PID<0.736.0> terminating
** (RuntimeError) Fail
    (example) lib/example/tasks/test_task.ex:3: Example.Tasks.TestTask.run/0
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<7.108098218/0 in Quantum.Executor.run/4>
    Args: []
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Scheduling job for execution #Reference<0.869436057.1393033218.155314>
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576460606610 (2020-03-11T10:52:30)
[debug] [:nonode@nohost][Elixir.Quantum.Executor] Task for job #Reference<0.869436057.1393033218.155314> started on node :nonode@nohost
[debug] [:nonode@nohost][Elixir.Quantum.Executor] Execute started for job #Reference<0.869436057.1393033218.155314>
[error] Task #PID<0.739.0> started from #PID<0.738.0> terminating
** (RuntimeError) Fail
    (example) lib/example/tasks/test_task.ex:3: Example.Tasks.TestTask.run/0
    (quantum) lib/quantum/executor.ex:141: anonymous fn/3 in Quantum.Executor.run/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<7.108098218/0 in Quantum.Executor.run/4>
    Args: []
```

Is there any way to use `Process.monitor` to receive `DOWN` messages when a job crashes?

Issue #415 sounds promising if it handles errors and will provide stack traces for those errors.

**Comment by maennchen** [comment]
Replaced by #453
