### ISSUE TITLE
I can't implement quantum

### ISSUE THREAD

**Issue by HaNdlezz** [quantum-elixir/quantum-core#431]
Hi,
Sorry my issue, but i can't implement quantum, i share as i trying configure quantum:

file shceduler.ex into lib folder:
`defmodule CourierStatus.Scheduler do
  use Quantum.Scheduler,
    otp_app: :courier_status
end`

Config into config.exs:
`config :courier_status, CourierStatus.Scheduler,
jobs: [
  {"* * * * *", fn -> IO.puts "PRUEBA" end}
]`

After, i up the application with mix phx.server, but i don't see the print in console,
o check the crontab for my current user (Ubuntu), and i don't see any crontab.

Sorry my issue, but i need configure this library really.

Cheers

**Comment by maennchen** [comment]
Please follow all the steps of the Setup Instructions: https://github.com/quantum-elixir/quantum-core/blob/master/README.md#setup

If the scheduler is not added to the supervision tree, it will not be started.

**Comment by HaNdlezz** [comment]
Ty for you answer :D,
my problem was solved, sorry my question,

Cheers
