### ISSUE TITLE
Quantum Storage for Mnesia (WIP)

### ISSUE THREAD

**Issue by sezaru** [quantum-elixir/quantum-core#438]
Hello there, inspired by QuantumStoragePersistentEts, I created an equivalent but using Mnesia.

You can check it out here: https://github.com/sezaru/quantum_storage_mnesia

It stills a WIP since I don't have tests for it, but it seems to work great.

If you don't mind, can you take a look and see if there is something that you see as a problem with it?

Also, I'm not sure what is the best way to handle the `nodes` parameter from mnesia, for now, it is hardcoded to `[node()]`, I'm not sure if I should handle remote nodes from it since I guess Quantum already does the synchronization for me right?
And if not, do you have any suggestions on how to send the nodes list to mnesia? I didn't find any way to send some custom data to the storage child_spec args for example.

**Comment by maennchen** [comment]
@sezaru That sounds great. As soon as you consider it ready, you‘re welcome to create a PR linking to your storage adapter.

For tests I recommend looking at the ets adapter. They’re quite basic.

I can‘t say that I know a lot about mnesia, I guess you‘d be better of asking questions to erlang / elixir support channels.
