### ISSUE TITLE
Problem: per second granularity defaulting to minute

### ISSUE THREAD

**Issue by markupguy** [quantum-elixir/quantum-core#443]
Hey there.

Using v3.0.1.

I'd expect the following to fire every 15 seconds, but sadly doesn't:

```
def ticker do
    MyApp.Scheduler.new_job()
    |> Quantum.Job.set_name(:ticker)
    |> Quantum.Job.set_schedule(%Crontab.CronExpression{extended: true, second: [15]})
    |> Quantum.Job.set_task(fn -> IO.puts "tick" end)
    |> MyApp.Scheduler.add_job()
  end
```
Any help would be appreciated.

**Comment by maennchen** [comment]
This CronExpression is wrong.

Use one of the following two ways to generate a cron expression:

* [`Crontab.CronExpression.Parser.parse/2`](https://hexdocs.pm/crontab/Crontab.CronExpression.Parser.html#parse/2)
* [`Crontab.CronExpression.html.sigil_e/2`](https://hexdocs.pm/crontab/Crontab.CronExpression.html#sigil_e/2)

The expression you constructed here is `15` and not `*/15`.

**Comment by markupguy** [comment]
Thanks @maennchen I did use the sigil but had the same problem, but I now see that I had to use */15, which "fixed" the issue.

**Comment by maennchen** [comment]
It doesn’t work for second precision, but for every other cron expression this helps you debug it: https://crontab.guru
