### ISSUE TITLE
Job option active

### ISSUE THREAD

**Issue by augnustin** [quantum-elixir/quantum-core#446]
Instead of writing:

```
config :app, App.Scheduler,
  jobs: if Mix.env() == :prod, do: [
    job_name: [
      schedule: "0 5 * * *",
      task: {App.JobModule, :job_method, []}
    ]
  ]
```

It would be nice to have:

```
config :app, App.Scheduler,
  jobs: [
    job_name: [
      schedule: "0 5 * * *",
      task: {App.JobModule, :job_method, []},
      active: Mix.env() == :prod
    ]
  ]
```

Definitely the same result, but more readable and kind of more the *elixir-way* of writing this IHMO.

I'm aware that if this has to do with environment config only, it could be set in `config/prod.exs` instead but I'm not fan of it because it could be forgotten in there (eg. for debugging). Putting it in `prod.exs` means "it should only run in this environment" while deactivating it in `config.exs` means "it is part of the app, simply I don't *need* to activate it right now in other environments".

**Comment by maennchen** [comment]
The *elixir-way* for doing that is definitely to put this into `prod.exs`. The configs are full fledged elixir scripts. Therefore this capability is not needed.

**Comment by augnustin** [comment]
This is disappointingly undiscussed. :disappointed: 

1. What if the test is not about environment but some other logic, like:

```
config :app, App.Scheduler,
  jobs: [
    job_name: [
      schedule: "0 5 * * *",
      task: {App.JobModule, :job_method, []},
      active: not is_nil System.get_env("DO_CRON_TASK")
    ]
  ]
```

2. I mentioned the *elixir-way* as the *functional-way* about having an `active`key to filter a list instead of `if cond, do: [element], else: []` which is heavy and ugly.

3. I meant my point when I said that it can be clearer to deactivate something instead of activating it within the options. Just like `unless` is better looking than `if not` in a condition.

4. This suggestion is 100% backward compatible (of course the default value of this option would be `true`), and must be pretty trivial to implement, so this would not change bring breaking changes, version controlling etc.

But in the end, if you are **so sure** about what your product needs, I wonder why contributions are accepted on this project. Good luck with yourself.

**Comment by maennchen** [comment]
I'm sorry if this looked arrogant, this was not my intention. A closed issue does not imply that discussions on the topic are not encouraged.

> What if the test is not about environment but some other logic, like:

I don't see the benefit of doing that since you can do exactly the same as in the first example.

> I mentioned the elixir-way as the functional-way about having an activekey to filter a list instead of if cond, do: [element], else: [] which is heavy and ugly.

This is the way lists are manipulated in elixir. If you'd like a more concise way it would be better to address that issue in elixir itself. (for example something like spreading arrays in JS)

> I meant my point when I said that it can be clearer to deactivate something instead of activating it within the options. Just like unless is better looking than if not in a condition.

Here we are talking about syntactic sugar of the language. What could be discussed is to for example allow and filter out `nil` from the list.

Example:

```elixir
config :app, App.Scheduler,
  jobs: [
    unless is_nil(System.get_env("DO_CRON_TASK")) do
      {"@daily", {Module, :daily, []}}
    end,
    {"*", {Module, :run_always, {}}
  ]
```

This could also be extended to allow nested list. This would allow something like that:

```elixir
config :app, App.Scheduler,
  jobs: [
    "CACHE_DOMAINS" |> System.get_env() |> String.split(",") |> Enum.map(&({"@daily", {Cache, :clear, [&1]}}),
    {"*", {Module, :run_always, {}}
  ]
```
