### ISSUE TITLE
From `config.exs` to module?

### ISSUE THREAD

**Issue by jechol** [quantum-elixir/quantum-core#448]
Whenever I change `config.exs`, all project files need to be recompiled.

How about changing configuration to happen in just module?

**Comment by maennchen** [comment]
@jechol You can change the configuration in code: https://hexdocs.pm/quantum/3.0.1/Quantum.html#c:init/1

You can also pass jobs to the use Quantum call.

I would still recommend to use the normal config mechanism though even if it recompiles some affected dependencies.

**Comment by jechol** [comment]
@maennchen Thanks.
