### ISSUE TITLE
Access to the queue

### ISSUE THREAD

**Issue by rmad1717** [quantum-elixir/quantum-core#451]
I have a certain scenario I am trying to achieve. Not sure if its possible, it not please tell me if any alternative solutions are possible. 
1. I am polling multiple APIs to 3rd parties very frequently for data syncing. 
2. I have application APIs(Endpoints) which allow my frontend to interact with my backend. 

Both 1 and 2 are part of the same codebase and I am trying to separate 1 and 2 into two different instances by running them conditionally inside Supervisor children. 
There are certain cases where I need to trigger a runtime task on occurence of some event. But I am unable to access the queue of Scheduler from the Application Server. Is it possible to do that or do I have to find some other way.

**Comment by maennchen** [comment]
@rmad1717 Do I understand it correctly that you want to run the scheduler only on some nodes but you do want to execute tasks on more nodes?

**Comment by rmad1717** [comment]
Yes. Kind off

**Comment by maennchen** [comment]
@rmad1717 You should be able to start a `Task.Supervisor` with a correct name and the you can use a custom `Quantum.RunStartegy` to actually run it.

Have a look at this to see an easy example of a run startegy: https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/run_strategy/all.ex

**Comment by maennchen** [comment]
@rmad1717 Does that solve your issue?

**Comment by maennchen** [comment]
Closed because of inactivity. Feel free to reopen this issue when needed.
