### ISSUE TITLE
Tests are not executed properly

### ISSUE THREAD

**Issue by pnezis** [quantum-elixir/quantum-core#466]
When executing `mix test` I am getting the following errors. 

```
 Quantum.ExecutionBroadcasterTest: failure on setup_all callback, all tests have been invalidated
     ** (EXIT from #PID<0.422.0>) exited in: ExUnit.CaptureLog.remove_capture(#PID<0.490.0>)
         ** (EXIT) {:error, :module_not_found}

Quantum.ExecutorTest: failure on setup_all callback, all tests have been invalidated
     ** (EXIT from #PID<0.3948.0>) exited in: ExUnit.CaptureLog.remove_capture(#PID<0.3949.0>)
         ** (EXIT) {:error, :module_not_found}
```

The same errors appear in all latest coveralls pipelines. **Notice that all remaining tests in the modules with issues are never executed and the tests appear as successful**

The culprits are the following tests. If I comment them out all other tests run without issues:

```
- Quantum.ExecutionBroadcasterTest: "invalid timezone will not create a crash"
- Quantum.ExecutorTest: "start_link/3 logs error"
- Quantum.ExucutorTest: "start_link/3 releases lock on error"
```

**Comment by maennchen** [comment]
Hmm. There seems to be an elixir issue about it: https://github.com/elixir-lang/elixir/issues/8507

**Comment by pnezis** [comment]
This seems to be introduced by #462. 

Test output after the addition of logger metadata:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1561963/100671295-ef56f180-3368-11eb-9359-6e5a52f611f3.png">

Test output on the previous PR (#459):

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/1561963/100671411-1f9e9000-3369-11eb-9b5a-56d224dec384.png">
