### ISSUE TITLE
can not perform, and show this warning

### ISSUE THREAD

**Issue by lianhj** [quantum-elixir/quantum-core#469]
[warning] <0.1627.0>@Elixir.Quantum.NodeSelectorBroadcaster:check_node/3:68 Node :"egame_cache@127.0.0.1" is not running. Job #Reference<0.405539817.1318060033.191976> could not be executed.

**Comment by maennchen** [comment]
@lianhj Can you please describe the error on detail?

* Quantum Version
* Debug Logs
* How many nodes is it running on?
* Was a deploy / node resize going on
* etc.

**Comment by bfolkens** [comment]
This happens to me with a 2 node cluster.  One node is configured to run the Quantum application, one without.  The log output above is the only log message shown (debug log threshold is set) besides the initial loading messages.
