### ISSUE TITLE
one time jobs

### ISSUE THREAD

**Issue by revati** [quantum-elixir/quantum-core#473]
Is it possible to add jobs that needs to be executed only once?
For example i need one job to be executed after 1 month.

Im using this library with persistance and it works well for cron like jobs, but i also have few commands that just needs to be executed once. One way would be to remove job once it is executed.

I know this isnt entirely scope of this library, but alternative would be to introduce some queue or something and it msot likely would mean some redis or rabbitmq, and it seems like unnceseary dependency. Would love to keep it in beam.

Maybe you could point me in right direction with alternative library with said functionality? Thanks.

**Comment by wesleimp** [comment]
I'm not sure if it's the `quantum`'s purpose. Maybe you could try something like [Oban](https://github.com/sorentwo/oban) for that.
