### ISSUE TITLE
Quantum.Job.new/1 doesn't accept custom name

### ISSUE THREAD

**Issue by LostKobrakai** [quantum-elixir/quantum-core#498]
`Quantum.Job.new/1` seems to accept all fields for a job, but not the name.

**Comment by maennchen** [comment]
@LostKobrakai Hm. It seems that I forgot to set `@doc false` on this. The idea is to use `YourScheduler.new_job()` and then call `Quantum.Job.set_name` on it. The reason for that is that the scheduler needs to pass some scheduler config to the job.

I see though that it would be nice to be able to configure all properties at once.

I'll have a look at this next week.

**Comment by LostKobrakai** [comment]
I‘m using ˋMyApp.Scheduler.new_job()ˋ, but as you guessed it‘s strange to be able to pass a keyword list, if the expectation is to use the explicit API. And otoh it‘s strange to not be able to set the name via the keyword list, if that‘s intended use. Also as usual with keyword list options it‘s even a silent error you need to discover with tests.

**Comment by maennchen** [comment]
@LostKobrakai What do you think of #500?

**Comment by maennchen** [comment]
@LostKobrakai Good point, I'll have a look, that all options are supported.

**Comment by maennchen** [comment]
@LostKobrakai Updated, ok now?

**Comment by LostKobrakai** [comment]
Looks good to me.
