### ISSUE TITLE
Check the existence of modules and functions in the jobs configuration at startup

### ISSUE THREAD

**Issue by Hentioe** [quantum-elixir/quantum-core#507]
I noticed that with non-existing modules or functions configured in jobs, Quantom doesn't give any errors or warnings on startup. For static jos configs, should they be checked for validity?

**Comment by maennchen** [comment]
@Hentioe That would be a good addition, a PR is welcome.

**Comment by Hentioe** [comment]
I'd be more than happy to open a PR if that's acceptable

**Comment by dannielb** [comment]
Hello @maennchen and @Hentioe!
I opened a [proposal](https://github.com/quantum-elixir/quantum-core/pull/523) to add a warning message for this case :)
