### ISSUE TITLE
seems like it doesn't work on docker container.

### ISSUE THREAD

**Issue by pyon123** [quantum-elixir/quantum-core#528]
I am a DevOps and trying to run Phoenix project on docker container. 
Currently it seems like there are some issues with quantum inside docker container. (Not sure it's quantum issue or not, since I am very new with Phoenix).
Elixir Quantum is running on top of linux cron? I've already install cron and nano, but there's no difference.

Let me attach code snip and the issue.

![image](https://user-images.githubusercontent.com/66934494/196496371-fe477474-ddc2-4e28-a6a0-2d0d35ce850a.png)

![image](https://user-images.githubusercontent.com/66934494/196496794-81cf6154-6d98-4a80-88ae-458b5e61ce23.png)

**Comment by maennchen** [comment]
@pyon123 Quantum is not based on unix cron and does not have any non-elixir dependencies.

Therefore it should work just fine in any normal environment which includes docker.

What are the issues you’re experiencing? The logs show no errors so far…

**Comment by pyon123** [comment]
Hi @maennchen 

Thanks for letting me know this. and sorry for the late reply. I thought I was already replied this.

It was my mistake. I am new with Elixir and Phoenix, so I thought the result: nil would be an issue. I've tested in deeper and understand everything is working fine. 

Thank you.
