### ISSUE TITLE
Is quantum deprecated?

### ISSUE THREAD

**Issue by IwoHerka** [quantum-elixir/quantum-core#583]
Hi, last release (3.5.0) was over a year ago. Are there any plans to continue development? If not, then perhaps someone can take over or, if not, repo should could be archived.

I'm asking because I'm using Quantum in production but I'm worried I will have to migrate away from it. 

Thanks!

**Comment by maennchen** [comment]
@IwoHerka It is not deprecated but I also don't have any plans for developing new features at the moment.

If there's new needs and/or people willing to contribute, this is welcome.
