### ISSUE TITLE
Using extended crontab expressions

### ISSUE THREAD

**Issue by jshickey** [quantum-elixir/quantum-core#628]
The documentation says that cron expressions are handled by the crontab library. That library supports using six positions for time that start with seconds. I tried using the ~e format described in the crontab docs with the config.exs but the ~e sigil is not recognized. What is the correct way to specify the crontab extended cron expressions with Quantum?

**Comment by maennchen** [comment]
https://hexdocs.pm/quantum/configuration.html#jobs-with-second-granularity

**Comment by jshickey** [comment]
Thanks for the reply.

Sorry about that!

Scott Hickey

Sent with [Proton Mail](https://proton.me/mail/home) secure email.
